"""Add secret field.

Revision ID: 004
Revises: 4ebffefee818
Create Date: 2026-03-11 13:49:40.748057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '004'
down_revision: Union[str, Sequence[str], None] = '4ebffefee818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nid_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name_bn', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('fathers_name', sa.String(length=50), nullable=True),
    sa.Column('mothers_name', sa.String(length=50), nullable=True),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('nid', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nid_data_id'), 'nid_data', ['id'], unique=False)
    op.create_index(op.f('ix_nid_data_nid'), 'nid_data', ['nid'], unique=True)
    op.drop_index(op.f('ix_niddata_id'), table_name='niddata')
    op.drop_index(op.f('ix_niddata_nid'), table_name='niddata')
    op.drop_table('niddata')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('niddata',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name_bn', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('fathers_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('mothers_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('nid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('niddata_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('niddata_pkey'))
    )
    op.create_index(op.f('ix_niddata_nid'), 'niddata', ['nid'], unique=True)
    op.create_index(op.f('ix_niddata_id'), 'niddata', ['id'], unique=False)
    op.drop_index(op.f('ix_nid_data_nid'), table_name='nid_data')
    op.drop_index(op.f('ix_nid_data_id'), table_name='nid_data')
    op.drop_table('nid_data')
    # ### end Alembic commands ###
