"""add date in nid table

Revision ID: 4ebffefee818
Revises: 8ef852787040
Create Date: 2026-03-11 11:55:20.474824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ebffefee818'
down_revision: Union[str, Sequence[str], None] = '8ef852787040'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('niddata', sa.Column('dob', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('niddata', 'dob')
    # ### end Alembic commands ###
