"""foreignkey

Revision ID: 8ef852787040
Revises: d96d91446a45
Create Date: 2026-03-11 11:45:53.494764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ef852787040'
down_revision: Union[str, Sequence[str], None] = 'd96d91446a45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('niddata', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'niddata', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'niddata', type_='foreignkey')
    op.drop_column('niddata', 'user_id')
    # ### end Alembic commands ###
